name: test_riw_order
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  # webviewx: ^0.2.1
  # webview_flutter: ^2.8.0
  # printing: ^5.9.1
  # pdf: ^3.8.1
  flutter_inappwebview: ^5.4.3+7
  flutter_downloader: ^1.8.0+1
  permission_handler: ^10.0.0
  jiffy: ^5.0.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

